name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install
      run: npm install
    - name: Test
      run: npm test    
    - name: Prepare App Config
      run: node ./scripts/updateAppConfig.js
      env:
        BUILD_NUMBER: ${{ github.run_id }}
        SERVER_URL: ${{ secrets.SERVER_URL }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        LOGS_SUBDOMAIN: ${{ secrets.LOGS_SUBDOMAIN }}
        LOGS_INPUT_TOKEN: ${{ secrets.LOGS_INPUT_TOKEN }}
    - name: expo configure
      uses: expo/expo-github-action@v5
      with:
        expo-packager: npm
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
    - name: expo publish
      run: expo publish